import numpy as np

DATA_PATH = "data"
TRAIN_PATH = "/moded" #"/train"

TRAIN_FILENAME = "./train.csv"
VALID_FILENAME = "./valid.csv"
CSV_COLS = ("filename","class")

IMG_HEIGHT = 294
IMG_WIDTH = 776
IMAGE_TARGET_SIZE = (IMG_HEIGHT,IMG_WIDTH)
RESCALE=1./255

BATCH_SIZE = 32
EPOCHS = 1
STEPS_PER_EPOCH = np.ceil(800/BATCH_SIZE)
VALIDATION_STEPS = 1

CONV_FILTERS = 8
POOL_SIZE = 2